dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user board password 'board'"
- psql -U postgres -c "create database boardDB owner board"
- psql -U postgres -c "ALTER USER board CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codacy-coverage
- pip install coverage
script:
- cd board
- python ./manage.py makemigrations
- python ./manage.py migrate --run-syncdb
- python ./manage.py test --keepdb
- coverage run --branch --source=. ./manage.py test --keepdb
- coverage xml
- python-codacy-coverage -r coverage.xml
branches:
  only:
  - develop
deploy:
  provider: heroku
  app: tryonboard-sprint1
  strategy: git
  api_key:
    secure: wv8RwHfaI6w9YvthCi5Tb+tu5vRGPsH61e5Az8ZK8ZSWTF7cxFfOngbV6KcpgQ1erngr7JrV7+kt9DjFk57wKGma2eTvJ1YJBHvZKUBdIxGqmYO9mOauAwjdY4WtKfc619tBX5yNbcRA5BwZopv8E7CwxZyRd/qjFqtS+N+9yCmpopXuph7eDMa5lAvI5CXkHgkMcQZgG6PPk9wtTNQMcmlKih+ik4rNx+D7IGXI/YgK8PUvOWDcDQR9HOsqbvcekdrN/eZdpFvVgxbY0+wZo+yOWZ0qCRpghw9FMMRUNOKxi6SczZKPANFMBGky78D/wc1ECD4wL7Rz3UpX2m3nPhqAImhce89AxXxdD3xhcNn0mQ/QUoaRI4Mv41pMn/+i4dZHQQCyLi6uwGZwdeNyEnxDhN4NhBlSfkto04YNHjpAXNfocGLVEXYGRuVIljXo/5uRBJ1ZTZXJnypOrlB4X54feB51v6myvAYf6kEKW2stqL067IP/FG4u01uVEALQBmFvBumLY/lyBIV/pTui5EUaAqL+WWaYJtmvgxs8TscBBqZ/ZpImVi5T/1joTq4mwHzw44SF+ILHahKSX4/NTPopSJgCepaHjt+Ga7fArio6CXxSZqUSKjTk7WYq2LszYH5Hy5sEkz9h/5L3QTEOplV2C6bYS6VhJsGVHWRbVjg=