dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user board password 'board'"
- psql -U postgres -c "ALTER ROLE board superuser"
- psql -U postgres -c "create database boardDB owner board"
- psql -U postgres -c "ALTER USER board CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codacy-coverage
- pip install coverage
script:
- cd board
- python ./manage.py makemigrations
- python ./manage.py migrate --run-syncdb
- python ./manage.py test --keepdb
- coverage run --branch --source=. ./manage.py test --keepdb
- coverage xml
- python-codacy-coverage -r coverage.xml
branches:
  only:
  - master
deploy:
  provider: heroku
  app: tryonboard-sprint1
  strategy: git
  api_key:
    secure: z3EyoSajp2+oB70IpY9N0ffgW/eXZiQH11IWQ25sdC709DvNAzBJBD69QnRfslVZAgEFmoFYmoKbr8lDWPwbt3G+iHEGEc9XqKkiJ7BhAE4FeOu6493tNd4ZVyzXJA0hKL2go0eIiWPCZtOLths1vQATYET9V2476Vy427fEztasIzLkD5fXnaDWt7PoJ8bzsv6UwnPATDvbMINOnUZQH0MYDyiY7Gvi2yPYmvCgkosXTdydU5BoFxG6SPLSJhz1UdjYJpsnAcZYIGaMyUy1ZHGa8Cg0YxNu6D65g6UYnncZgpTF4QTQyKM5M/ctmif+9zDMgV2F23cxFSndU+ZFprkw4nSmROb0qodFS0RFOixf+9VUnC7Obbd1Z39a/8JNPvEhC+6FYqDXG9a6RI1sOJRSDzNA3zusPHe//Mww/kqD0hEg62wAjo8TOXsXGVcBkxCV7mWEQIgYMHlRvR7KVF+3+3NT5an2eN5jtFjp3O54AQ7LGZk+lDf1OY/HGuzSbi3Cb4lIsrKHj1slsQgmgrfV/GvFTS6z8ZGU2KtYDvYsDQpyfimCo9VODgyETPr3lRoZcsDGh3PiJwJNFaN9zFJBz4kOaWO+taxC71VLdWEEw1z7ugDs1kx/Ubay2wqVmY636IRM/eqPBpMyrrgcGFTVu6vCvH5rrw4kknvGotY=
