dist: xenial
services:
- postgresql
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user board password 'board'"
- psql -U postgres -c "ALTER ROLE board superuser"
- psql -U postgres -c "create database boardDB owner board"
- psql -U postgres -c "ALTER USER board CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codacy-coverage
- pip install coverage
script:
- cd board
- python ./manage.py makemigrations
- python ./manage.py migrate --run-syncdb
- python ./manage.py test --keepdb
- coverage run --branch --source=. ./manage.py test --keepdb
- coverage xml
- python-codacy-coverage -r coverage.xml
deploy:
  provider: heroku
  app: tryonboard-sprint1
  strategy: git
  api_key:
    secure: cIQuU1EEQJBx8Di/iX7WpN+ANVcSXEn0ODPKcgJ0gP4o2NTLhwSD4IQc97TsHBCsCAaZBro8vxrpxajxhrysxEu/gstfQuJZDgWBH/vts44pbyFFaSwWlYCrQ/yWJCO3svx7CcKKFqNkXIQq1on2i/Ql+yxTnvZHF2tWbw3Kye4I352C5J1gJarH2jiCbSv0VeLQfQXMaGQjA98TRkgIwZmOz55Ij1Mca/sum/eIfh6oKWaLf94sT8UtI3WNTXRK/riUSEg4t2p4mxQMv/NbAXbXACUKuD2HKuALo8O2Ssr2EkQK7KdpixEkUE2ynXPpTzreGuwch1h3L5HpTJOJ/nmiPHEBeNlhUB684KjFVO9fqOl060Hg5jFxOainVHbPgFJFUtJxBiA+sudB5DcSO7OHV9Vg28I2eZ/Z4Vcb3vbibAR0HLpUNoRcS3WnSANpchheOq/BN2T6nIbw/oPxzLEm4GC2uyuUy8UYxebWwsfxJw22LB7i5dLN6hdQ8Te8jQoGJVljsn7VYeAgngqp4TVQ9k3SCzJ0ciOfCdXCiKNdBuRb7N7Uzmdi+qcxyAYB78bE4oHwKJDlPWeO1BK371gPOBpuEjrSEFQxFvU65NleW+eLxAaoC1YN04EwFhtAh4IbzoSy773pWPq00moQcXyD7cKfclwzb89xf7FzLE0=